default_platform(:android)

platform :android do
  desc "Build Android Release Bundle (AAB)"
  lane :build do
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "./"
    )
  end

  desc "Build and Deploy to Google Play Store (Production Track)"
  lane :deploy do
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "./"
    )

    key_file = ENV["PLAY_STORE_JSON_KEY_PATH"]
    key_file = File.expand_path('../pc-api-key.json', __dir__) if key_file.nil? || key_file.empty? || !File.exist?(key_file)
    key_file = File.expand_path('../../pc-api-key.json', __dir__) if !File.exist?(key_file)

    upload_to_play_store(
      track: 'production',
      json_key: key_file,
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      skip_upload_apk: true,
      skip_upload_metadata: false,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
