default_platform(:android)

platform :android do
  desc "Build Android Release Bundle (AAB)"
  lane :build do
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "./"
    )
  end

  desc "Build and Deploy to Google Play Store (Production Track)"
  lane :deploy do
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "./"
    )

    upload_to_play_store(
      track: 'production',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      skip_upload_apk: true,
      skip_upload_metadata: false,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
