name: react-native-android-build-apk

on:
  push:
    branches:
      - master

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies with Yarn
        run: yarn install

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: "temurin"
      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies with Yarn
        run: yarn install
      - name: Build Android Release
        run: |
          cd android && chmod +x ./gradlew && ./gradlew assembleRelease
          # Generate a unique file name based on timestamp
          timestamp=$(date +"%d%m_%H%M")
          apk_name="My_Rooms_$timestamp.apk"
          mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/$apk_name
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.build-android.outputs.apk_name }}
          path: android/app/build/outputs/apk/release/$apk_name
